apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: taskapp
spec:
  replicas: 3

  selector:
    matchLabels:
      app: backend

  template:
    metadata:
      labels:
        app: backend

    spec:
      containers:
      - name: backend

        image: ghcr.io/tes-balo/taskapp-backend:latest@sha256:1e9dddf3794c79f2b7f1519ef8d9d1cd34d104c8ccf728ab7d4197add203fddc

        imagePullPolicy: Always

        ports:
        - containerPort: 5000

        envFrom:
        - configMapRef:
            name: backend-config

        - secretRef:
            name: backend-secret

        resources:
          requests:
            cpu: 100m
            memory: 128Mi

          limits:
            cpu: 500m
            memory: 512Mi

        readinessProbe:
          httpGet:
            path: /api/health
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 5

        livenessProbe:
          httpGet:
            path: /api/health
            port: 5000

          initialDelaySeconds: 20
          periodSeconds: 10