apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: taskapp
type: Opaque
stringData:
  DATABASE_USER: taskapp
  DATABASE_PASSWORD: taskapp123
  SECRET_KEY: change-me-super-secret