---
k3s_version: v1.33.3+k3s1

k3s_server_ip: "{{ hostvars['k3s-server']['ansible_default_ipv4']['address'] }}"

k3s_server_url: "https://{{ k3s_server_ip }}:6443"

k3s_install_script: https://get.k3s.io